#!/bin/bash


echo "Today is `date`."
echo "You are in `pwd` and your host is `hostname`."
echo "Enjoy." #with double quotes, asterisks are not interpreted but most other commands are interpreted


echo "Finished."
